### ISSUE TITLE
rbspy doesn't support Ruby 3.3.2 yet

### ISSUE THREAD

**Issue by technicalpickles** [rubyatscale/singed#37]
We updated to ruby 3.3.2, and got this error when using the CLI:

```
❯ bin/singed bin/tapioca dsl
🔥📈 Singed needs to run as root, but will drop permissions back to your user. Prompting with sudo now...
$ sudo --preserve-env rbspy record --format speedscope --file tmp/speedscope/speedscope-cli-20240603122127.json --silent -- bin/tapioca dsl
Dropping permissions: running Ruby command as user josh.nichols
rbspy is recording traces. Press Ctrl+C to stop.
Wrote raw data to /Users/josh.nichols/Library/Caches/rbspy/2024-06-03-Y4xcYuW4vl.raw.gz
Wrote formatted output to tmp/speedscope/speedscope-cli-20240603122127.json
Something went wrong while rbspy was sampling the process. Here's what we know:
- new spy
- get ruby VM state
- rbspy doesn't support Ruby 3.3.2 yet. If this is a new patch-level version of Ruby, you can try using `--force-version` with the previous version number.
/Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/singed-0.2.1/lib/singed/cli.rb:157:in `system': Command failed with exit 1: sudo (RuntimeError)
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/singed-0.2.1/lib/singed/cli.rb:157:in `sudo'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/singed-0.2.1/lib/singed/cli.rb:93:in `block in run'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/singed-0.2.1/lib/singed/cli.rb:98:in `block in run'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/lib/bundler.rb:424:in `block in with_unbundled_env'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/lib/bundler.rb:679:in `with_env'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/lib/bundler.rb:424:in `with_unbundled_env'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/singed-0.2.1/lib/singed/cli.rb:97:in `run'
	from /Users/josh.nichols/.local/share/mise/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/singed-0.2.1/exe/singed:9:in `<top (required)>'
	from bin/singed:27:in `load'
	from bin/singed:27:in `<main>'
```

**Comment by dduugg** [comment]
Looks like rbspy currently supports ruby 4, I assume this is outdated. Feel free to re-open if I'm mistaken. 🙇‍♂️
